//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int teacherId { get; set; }
        public string teacherName { get; set; }
        public string subject { get; set; }
        public string matter { get; set; }
        public string @class { get; set; }
        public int questionnaire { get; set; }
    }
}
